#!/bin/bash
docker run --rm -it \
	-v $PWD/src:/app/src \
	-v $PWD/testing:/app/testing \
	-v $PWD/package.json:/app/package.json \
	--add-host=graphql.kube.simpleview.io:192.168.50.100 \
	sv-email-client:local /bin/sh